# Generated by Django 3.0.4 on 2020-07-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('currentStat', models.CharField(max_length=20)),
                ('jobtitle', models.CharField(max_length=50)),
                ('reviewHeadline', models.CharField(max_length=50)),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
