# Generated by Django 3.0.4 on 2020-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerreview', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
